### ISSUE TITLE
Count without placing component

### ISSUE THREAD

**Issue by NewOldMax** [MicheleBertoli/react-count-to#10]
Hi,
Is there a way to get counter works without placing component?
For example, I use `react-intl` to format currency values and can't provide a tag as value
````javascript
<FormattedNumber
    value={100}            <====
    style="currency"
    currency="EUR"
    currencyDisplay="symbol"
    maximumFractionDigits={0}
/>
````
and it would be nice to use something like
````javascript
<FormattedNumber
    value={CountTo.count({from: 0, to: 100)} <====
    style="currency"
    currency="EUR"
    currencyDisplay="symbol"
    maximumFractionDigits={0}
/>
````

**Comment by pwolaq** [comment]
I can think of something like:
```javascript
<CountTo to={1234} speed={1234}>
{(value) => {
    <FormattedNumber
        value={value}
        style="currency"
        currency="EUR"
        currencyDisplay="symbol"
        maximumFractionDigits={0}
    />
}
</CountTo>
```
this shouldn't be hard to implement - I can prepare PR on Saturday/Sunday if @MicheleBertoli approves this idea

**Comment by MicheleBertoli** [comment]
Good point @NewOldMax, thanks!

❤️ Function as Child @pwolaq.
I absolutely approve, and I look forward to your solution.

As I [said](https://github.com/MicheleBertoli/react-count-to/pull/9) I would love to add you to the repo, since you have great ideas for the package and already contributed to it multiple times.

**Comment by MicheleBertoli** [comment]
Good point @NewOldMax, thanks!

❤️ Function as Child @pwolaq.
I absolutely approve, and I look forward to your solution.

As I [said](https://github.com/MicheleBertoli/react-count-to/pull/9) I would love to add you to the repo, since you have great ideas for the package and already contributed to it multiple times. What do you think?

**Comment by pwolaq** [comment]
well, I don't have much experience with managing repository but I could try :)

**Comment by MicheleBertoli** [comment]
v0.7.0 🚀
Thank you very much @pwolaq

**Comment by MicheleBertoli** [comment]
Are you on twitter @pwolaq?

**Comment by pwolaq** [comment]
no, unfortunately I'm not
