### ISSUE TITLE
how to redraw / restart counter via another handler in parent component

### ISSUE THREAD

**Issue by azulkipli** [MicheleBertoli/react-count-to#8]

**Comment by MicheleBertoli** [comment]
Hello @azulkipli, thank for opening the issue.

The `CountTo` component exposes a `start` method that you can access using refs, as follows:

```jsx
<CountTo ref={(element => (this.element = element))} ... />
<button onClick={() => this.element.start()}>restart</button>
```

I couldn't think of a use case where you need to restart the counter (without changing the props), can you please explain me a little bit more so that I can find a better solution?
